ALTER TABLE "User"
ADD COLUMN "avgRating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "totalReviews" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Booking"
ALTER COLUMN "durationHours" TYPE DOUBLE PRECISION USING "durationHours"::DOUBLE PRECISION;
